apiVersion: v1
kind: Service
metadata:
  name: azure-qdrant-lb
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 6333
    protocol: TCP
    targetPort: 6333
  - name: grpc
    port: 6334
    protocol: TCP
    targetPort: 6334
  - name: p2p
    port: 6335
    protocol: TCP
    targetPort: 6335
  selector:
    app: qdrant
    app.kubernetes.io/instance: azure-qdrant
    app.kubernetes.io/name: qdrant

