# Deploy Qdrant locally with Docker on MacOS
version: '3.1'

services:
  vectordb:
    image: qdrant/qdrant:v0.10.2
    restart: always
    ports:
      - '127.0.0.1:6333:6333'
    volumes:
      - ~/workspace/mydata/qdrant:/qdrant/storage
      - ./qdrant.yaml:/qdrant/config/production.yaml
